version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Serviço do Sistema de Mensageria Redis
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"

  # Opcional: Serviço do Backend (Node.js)
  # Você pode adicionar isso depois de criar a estrutura do seu projeto Node.js
  # app:
  #   build: ./backend
  #   command: npm run dev
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #     REDIS_URL: redis://redis:6379
      
volumes:
  postgres_data: